# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: simpleFeatureMessages.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='simpleFeatureMessages.proto',
  package='protos',
  syntax='proto3',
  serialized_pb=_b('\n\x1bsimpleFeatureMessages.proto\x12\x06protos\"\x8f\x01\n\x12ProtoSimpleFeature\x12\x0c\n\x04geom\x18\x01 \x01(\x0c\x12:\n\x08metadata\x18\x02 \x03(\x0b\x32(.protos.ProtoSimpleFeature.MetadataEntry\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_PROTOSIMPLEFEATURE_METADATAENTRY = _descriptor.Descriptor(
  name='MetadataEntry',
  full_name='protos.ProtoSimpleFeature.MetadataEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='protos.ProtoSimpleFeature.MetadataEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='protos.ProtoSimpleFeature.MetadataEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=_descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001')),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=136,
  serialized_end=183,
)

_PROTOSIMPLEFEATURE = _descriptor.Descriptor(
  name='ProtoSimpleFeature',
  full_name='protos.ProtoSimpleFeature',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='geom', full_name='protos.ProtoSimpleFeature.geom', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='metadata', full_name='protos.ProtoSimpleFeature.metadata', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_PROTOSIMPLEFEATURE_METADATAENTRY, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=40,
  serialized_end=183,
)

_PROTOSIMPLEFEATURE_METADATAENTRY.containing_type = _PROTOSIMPLEFEATURE
_PROTOSIMPLEFEATURE.fields_by_name['metadata'].message_type = _PROTOSIMPLEFEATURE_METADATAENTRY
DESCRIPTOR.message_types_by_name['ProtoSimpleFeature'] = _PROTOSIMPLEFEATURE

ProtoSimpleFeature = _reflection.GeneratedProtocolMessageType('ProtoSimpleFeature', (_message.Message,), dict(

  MetadataEntry = _reflection.GeneratedProtocolMessageType('MetadataEntry', (_message.Message,), dict(
    DESCRIPTOR = _PROTOSIMPLEFEATURE_METADATAENTRY,
    __module__ = 'simpleFeatureMessages_pb2'
    # @@protoc_insertion_point(class_scope:protos.ProtoSimpleFeature.MetadataEntry)
    ))
  ,
  DESCRIPTOR = _PROTOSIMPLEFEATURE,
  __module__ = 'simpleFeatureMessages_pb2'
  # @@protoc_insertion_point(class_scope:protos.ProtoSimpleFeature)
  ))
_sym_db.RegisterMessage(ProtoSimpleFeature)
_sym_db.RegisterMessage(ProtoSimpleFeature.MetadataEntry)


_PROTOSIMPLEFEATURE_METADATAENTRY.has_options = True
_PROTOSIMPLEFEATURE_METADATAENTRY._options = _descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001'))
# @@protoc_insertion_point(module_scope)
