# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: extentMessages.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='extentMessages.proto',
  package='protos',
  syntax='proto3',
  serialized_pb=_b('\n\x14\x65xtentMessages.proto\x12\x06protos\"\'\n\x08ProtoCRS\x12\x0c\n\x04\x65psg\x18\x01 \x01(\x05\x12\r\n\x05proj4\x18\x02 \x01(\t\"E\n\x0bProtoExtent\x12\x0c\n\x04xmin\x18\x01 \x01(\x01\x12\x0c\n\x04ymin\x18\x02 \x01(\x01\x12\x0c\n\x04xmax\x18\x03 \x01(\x01\x12\x0c\n\x04ymax\x18\x04 \x01(\x01\"Z\n\x14ProtoProjectedExtent\x12#\n\x06\x65xtent\x18\x01 \x01(\x0b\x32\x13.protos.ProtoExtent\x12\x1d\n\x03\x63rs\x18\x02 \x01(\x0b\x32\x10.protos.ProtoCRS\"s\n\x1cProtoTemporalProjectedExtent\x12#\n\x06\x65xtent\x18\x01 \x01(\x0b\x32\x13.protos.ProtoExtent\x12\x1d\n\x03\x63rs\x18\x02 \x01(\x0b\x32\x10.protos.ProtoCRS\x12\x0f\n\x07instant\x18\x03 \x01(\x04\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_PROTOCRS = _descriptor.Descriptor(
  name='ProtoCRS',
  full_name='protos.ProtoCRS',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='epsg', full_name='protos.ProtoCRS.epsg', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='proj4', full_name='protos.ProtoCRS.proj4', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=32,
  serialized_end=71,
)


_PROTOEXTENT = _descriptor.Descriptor(
  name='ProtoExtent',
  full_name='protos.ProtoExtent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='xmin', full_name='protos.ProtoExtent.xmin', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ymin', full_name='protos.ProtoExtent.ymin', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='xmax', full_name='protos.ProtoExtent.xmax', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ymax', full_name='protos.ProtoExtent.ymax', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=73,
  serialized_end=142,
)


_PROTOPROJECTEDEXTENT = _descriptor.Descriptor(
  name='ProtoProjectedExtent',
  full_name='protos.ProtoProjectedExtent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='extent', full_name='protos.ProtoProjectedExtent.extent', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='crs', full_name='protos.ProtoProjectedExtent.crs', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=144,
  serialized_end=234,
)


_PROTOTEMPORALPROJECTEDEXTENT = _descriptor.Descriptor(
  name='ProtoTemporalProjectedExtent',
  full_name='protos.ProtoTemporalProjectedExtent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='extent', full_name='protos.ProtoTemporalProjectedExtent.extent', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='crs', full_name='protos.ProtoTemporalProjectedExtent.crs', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='instant', full_name='protos.ProtoTemporalProjectedExtent.instant', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=236,
  serialized_end=351,
)

_PROTOPROJECTEDEXTENT.fields_by_name['extent'].message_type = _PROTOEXTENT
_PROTOPROJECTEDEXTENT.fields_by_name['crs'].message_type = _PROTOCRS
_PROTOTEMPORALPROJECTEDEXTENT.fields_by_name['extent'].message_type = _PROTOEXTENT
_PROTOTEMPORALPROJECTEDEXTENT.fields_by_name['crs'].message_type = _PROTOCRS
DESCRIPTOR.message_types_by_name['ProtoCRS'] = _PROTOCRS
DESCRIPTOR.message_types_by_name['ProtoExtent'] = _PROTOEXTENT
DESCRIPTOR.message_types_by_name['ProtoProjectedExtent'] = _PROTOPROJECTEDEXTENT
DESCRIPTOR.message_types_by_name['ProtoTemporalProjectedExtent'] = _PROTOTEMPORALPROJECTEDEXTENT

ProtoCRS = _reflection.GeneratedProtocolMessageType('ProtoCRS', (_message.Message,), dict(
  DESCRIPTOR = _PROTOCRS,
  __module__ = 'extentMessages_pb2'
  # @@protoc_insertion_point(class_scope:protos.ProtoCRS)
  ))
_sym_db.RegisterMessage(ProtoCRS)

ProtoExtent = _reflection.GeneratedProtocolMessageType('ProtoExtent', (_message.Message,), dict(
  DESCRIPTOR = _PROTOEXTENT,
  __module__ = 'extentMessages_pb2'
  # @@protoc_insertion_point(class_scope:protos.ProtoExtent)
  ))
_sym_db.RegisterMessage(ProtoExtent)

ProtoProjectedExtent = _reflection.GeneratedProtocolMessageType('ProtoProjectedExtent', (_message.Message,), dict(
  DESCRIPTOR = _PROTOPROJECTEDEXTENT,
  __module__ = 'extentMessages_pb2'
  # @@protoc_insertion_point(class_scope:protos.ProtoProjectedExtent)
  ))
_sym_db.RegisterMessage(ProtoProjectedExtent)

ProtoTemporalProjectedExtent = _reflection.GeneratedProtocolMessageType('ProtoTemporalProjectedExtent', (_message.Message,), dict(
  DESCRIPTOR = _PROTOTEMPORALPROJECTEDEXTENT,
  __module__ = 'extentMessages_pb2'
  # @@protoc_insertion_point(class_scope:protos.ProtoTemporalProjectedExtent)
  ))
_sym_db.RegisterMessage(ProtoTemporalProjectedExtent)


# @@protoc_insertion_point(module_scope)
