# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: featureMessages.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='featureMessages.proto',
  package='protos',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x15\x66\x65\x61tureMessages.proto\x12\x06protos\"P\n\x15ProtoFeatureCellValue\x12\x0c\n\x04geom\x18\x01 \x01(\x0c\x12)\n\tcellValue\x18\x02 \x01(\x0b\x32\x16.protos.ProtoCellValue\"/\n\x0eProtoCellValue\x12\r\n\x05value\x18\x01 \x01(\x01\x12\x0e\n\x06zindex\x18\x02 \x01(\x01\x62\x06proto3')
)




_PROTOFEATURECELLVALUE = _descriptor.Descriptor(
  name='ProtoFeatureCellValue',
  full_name='protos.ProtoFeatureCellValue',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='geom', full_name='protos.ProtoFeatureCellValue.geom', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cellValue', full_name='protos.ProtoFeatureCellValue.cellValue', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=33,
  serialized_end=113,
)


_PROTOCELLVALUE = _descriptor.Descriptor(
  name='ProtoCellValue',
  full_name='protos.ProtoCellValue',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='protos.ProtoCellValue.value', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='zindex', full_name='protos.ProtoCellValue.zindex', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=115,
  serialized_end=162,
)

_PROTOFEATURECELLVALUE.fields_by_name['cellValue'].message_type = _PROTOCELLVALUE
DESCRIPTOR.message_types_by_name['ProtoFeatureCellValue'] = _PROTOFEATURECELLVALUE
DESCRIPTOR.message_types_by_name['ProtoCellValue'] = _PROTOCELLVALUE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ProtoFeatureCellValue = _reflection.GeneratedProtocolMessageType('ProtoFeatureCellValue', (_message.Message,), dict(
  DESCRIPTOR = _PROTOFEATURECELLVALUE,
  __module__ = 'featureMessages_pb2'
  # @@protoc_insertion_point(class_scope:protos.ProtoFeatureCellValue)
  ))
_sym_db.RegisterMessage(ProtoFeatureCellValue)

ProtoCellValue = _reflection.GeneratedProtocolMessageType('ProtoCellValue', (_message.Message,), dict(
  DESCRIPTOR = _PROTOCELLVALUE,
  __module__ = 'featureMessages_pb2'
  # @@protoc_insertion_point(class_scope:protos.ProtoCellValue)
  ))
_sym_db.RegisterMessage(ProtoCellValue)


# @@protoc_insertion_point(module_scope)
